/**
 * Per-org PHI encryption key management using envelope encryption.
 *
 * Architecture:
 * - Master key (KEK): AWS KMS CMK, identified by AWS_KMS_KEY_ID
 * - Per-org data key (DEK): AES-256 key generated by KMS, stored encrypted in org settings
 * - PHI encryption: Use DEK (not master key) for actual data encryption
 *
 * Benefits:
 * - Key rotation: re-encrypt org's DEK via KMS without re-encrypting all data
 * - Org churn: delete/disable org's DEK → org's PHI becomes inaccessible
 * - Audit: AWS CloudTrail tracks every DEK decryption (key usage logging)
 *
 * Fallback: When AWS_KMS_KEY_ID is not set, returns null → phi-encryption.ts
 * uses the shared PHI_ENCRYPTION_KEY env var (existing behavior).
 */

import { createCipheriv, createDecipheriv, randomBytes } from "crypto";
import { logger } from "./logger";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 12;
const AUTH_TAG_LENGTH = 16;

// In-memory DEK cache (30-minute TTL per org)
const dekCache = new Map<string, { key: Buffer; expiresAt: number }>();
const DEK_TTL_MS = 30 * 60 * 1000;

// Per-org DEK generation lock — prevents concurrent generation race condition
// where two requests both see "no DEK" and overwrite each other.
const dekGenLocks = new Map<string, Promise<Buffer | null>>();

function getCachedDek(orgId: string): Buffer | null {
  const entry = dekCache.get(orgId);
  if (entry && Date.now() < entry.expiresAt) return entry.key;
  dekCache.delete(orgId);
  return null;
}

function cacheDek(orgId: string, key: Buffer): void {
  dekCache.set(orgId, { key, expiresAt: Date.now() + DEK_TTL_MS });
}

export function invalidateOrgDek(orgId: string): void {
  dekCache.delete(orgId);
}

/**
 * Get or create the DEK for an org.
 * Returns null if KMS is not configured (caller uses shared key).
 */
export async function getOrgDataKey(orgId: string): Promise<Buffer | null> {
  const kmsKeyId = process.env.AWS_KMS_KEY_ID;
  if (!kmsKeyId) return null; // KMS not configured — use shared key

  // Check cache first (fast path, no lock needed)
  const cached = getCachedDek(orgId);
  if (cached) return cached;

  // Serialize DEK generation per org to prevent concurrent requests from
  // both generating a new DEK and overwriting each other.
  const existing = dekGenLocks.get(orgId);
  if (existing) return existing;

  const work = _getOrCreateOrgDataKey(orgId, kmsKeyId);
  dekGenLocks.set(orgId, work);
  try {
    return await work;
  } finally {
    dekGenLocks.delete(orgId);
  }
}

async function _getOrCreateOrgDataKey(orgId: string, kmsKeyId: string): Promise<Buffer | null> {
  // Lazy import to avoid requiring @aws-sdk/client-kms when KMS not used
  const { KMSClient, GenerateDataKeyCommand, DecryptCommand } = await import("@aws-sdk/client-kms");
  const kms = new KMSClient({ region: process.env.AWS_REGION || "us-east-1" });

  // Lazily import storage to avoid circular dependency
  const { storage } = await import("../storage");
  const org = await storage.getOrganization(orgId);

  const encryptedDek = (org?.settings as any)?.encryptedDataKey as string | undefined;

  if (!encryptedDek) {
    // Generate new DEK for this org
    logger.info({ orgId }, "Generating new per-org DEK via KMS");
    const result = await kms.send(new GenerateDataKeyCommand({
      KeyId: kmsKeyId,
      KeySpec: "AES_256",
      EncryptionContext: { orgId }, // Binds encrypted DEK to this org
    }));

    const dek = Buffer.from(result.Plaintext!);
    const cipherDek = Buffer.from(result.CiphertextBlob!).toString("base64");

    // Persist encrypted DEK to org settings
    await storage.updateOrganization(orgId, {
      settings: {
        ...(org?.settings || {}),
        encryptedDataKey: cipherDek,
        kmsKeyId,
      } as any,
    });

    cacheDek(orgId, dek);
    return dek;
  }

  // Decrypt existing DEK
  const result = await kms.send(new DecryptCommand({
    KeyId: kmsKeyId,
    CiphertextBlob: Buffer.from(encryptedDek, "base64"),
    EncryptionContext: { orgId },
  }));

  const dek = Buffer.from(result.Plaintext!);
  cacheDek(orgId, dek);
  return dek;
}

/**
 * Encrypt a PHI field using the org's DEK (or shared key if KMS not configured).
 * Falls back gracefully to the shared-key encryptField() from phi-encryption.ts.
 */
export async function encryptFieldForOrg(plaintext: string, orgId: string): Promise<string> {
  let key: Buffer | null = null;
  try {
    key = await getOrgDataKey(orgId);
  } catch (err) {
    logger.warn({ orgId, err }, "KMS key fetch failed — falling back to shared PHI key");
  }

  if (!key) {
    // Fallback to shared key
    const { encryptField } = await import("./phi-encryption");
    return encryptField(plaintext);
  }

  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, key, iv, { authTagLength: AUTH_TAG_LENGTH } as any);
  const encrypted = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const authTag = (cipher as any).getAuthTag();
  const packed = Buffer.concat([iv, encrypted, authTag]);
  return `enc_v2_${orgId.slice(0, 8)}:${packed.toString("base64")}`;
}

/**
 * Decrypt a PHI field, automatically routing to org-scoped or shared key
 * based on the encryption prefix.
 */
export async function decryptFieldForOrg(encrypted: string, orgId: string): Promise<string> {
  // Legacy shared-key format
  if (encrypted.startsWith("enc_v1:")) {
    const { decryptField } = await import("./phi-encryption");
    return decryptField(encrypted);
  }

  // Per-org KMS format: enc_v2_{orgPrefix}:
  if (encrypted.startsWith("enc_v2_")) {
    const key = await getOrgDataKey(orgId);
    if (!key) throw new Error(`Cannot decrypt per-org PHI: KMS not configured for org ${orgId}`);

    const colonIdx = encrypted.indexOf(":");
    const payload = encrypted.slice(colonIdx + 1);
    const packed = Buffer.from(payload, "base64");
    const iv = packed.subarray(0, IV_LENGTH);
    const authTag = packed.subarray(packed.length - AUTH_TAG_LENGTH);
    const ciphertext = packed.subarray(IV_LENGTH, packed.length - AUTH_TAG_LENGTH);

    const decipher = createDecipheriv(ALGORITHM, key, iv, { authTagLength: AUTH_TAG_LENGTH } as any);
    (decipher as any).setAuthTag(authTag);
    return decipher.update(ciphertext) + decipher.final("utf8");
  }

  // Plain text (encryption not configured at time of write)
  return encrypted;
}
